services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.3.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/nearquake:/usr/src/app/logs
    healthcheck:
      test: [ "CMD", "python", "main.py" ]
      interval: 600s
      retries: 5
    restart: always
    env_file: .env
    networks:
      - nearquake-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${NEARQUAKE_USERNAME}
      POSTGRES_PASSWORD: ${NEARQUAKE_PASSWORD}
      POSTGRES_DB: ${NEARQUAKE_DATABASE}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    restart: always
    networks:
      - nearquake-network
networks:
  nearquake-network:
  
volumes:
  postgres-db-volume: