version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo
    logging:
        options:
            max-size: 10m
            max-file: "3"
    ports:
      - "5432:5432"

  airflow:
    image: nearquake
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file: .env
    logging:
        options:
            max-size: 10m
            max-file: "3"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dag:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
