version: '3.4'

services:
  nearquake_webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nearquake_webserver
    networks:
      - nearquake_network
    ports:
      - 3000:${PORT:-3000}

networks:
  nearquake_network:
    driver: bridge
    name: nearquake_network