version: '3.4'

services:
  earthquake.usgs.gov:
    image: earthquake.usgs.gov.cron:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - my_network

networks:
  my_network: