version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  nearquake:
    image: puckel/docker-airflow:1.10.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_DEPS: psycopg2-binary==2.8.6; tqdm==4.56.0; tweepy==3.9.0
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      - LOAD_EX=nd
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo
    volumes:
      - ./dag:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
