services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.3.0
    build:
      context: .
    container_name: earthquake_bot
    volumes:
      - /var/log/nearquake:/usr/src/app/logs
    restart: always
    env_file: .env
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
    networks:
      - nearquake-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${NEARQUAKE_USERNAME}
      POSTGRES_PASSWORD: ${NEARQUAKE_PASSWORD}
      POSTGRES_DB: ${NEARQUAKE_DATABASE}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    env_file: .env
    restart: always
    networks:
      - nearquake-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NEARQUAKE_USERNAME} -d ${NEARQUAKE_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nearquake-network:

volumes:
  postgres-db-volume: