version: '3.4'

services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - my_network

networks:
  my_network: