version: '3.4'

services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.0.6
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/cron.log:/var/log/cron.log
    env_file: .env
    networks:
      - nearquake-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${NEARQUAKE_USERNAME}
      POSTGRES_PASSWORD: ${NEARQUAKE_PASSWORD}
      POSTGRES_DB: ${NEARQUAKE_DATABASE}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - nearquake-network

networks:
  nearquake-network:
  
volumes:
  postgres-db-volume: