version: '3.4'
services:
  nearquake:
    build:
      context: .
    image: anelso42/nearquake
    container_name: nearquake
    env_file: .env
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: $NEARQUAKE_USERNAME
      POSTGRES_PASSWORD: $NEARQUAKE_PASSWORD
      POSTGRES_DB: $NEARQUAKE_DATABASE
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always