version: '3.4'

services:
  earthquake_usgs:
    image: earthquake_usgs_cron:1.0.2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/log/nearquake:/usr/src/app/logs
    env_file: .env