import logging

from google import genai

from nearquake.config import _nearquake_secrets
from nearquake.utils.logging_utils import (get_logger, log_api_request,
                                           log_api_response, log_error,
                                           log_info)

_logger = get_logger(__name__)

client = genai.Client(api_key=_nearquake_secrets.get("GEMINI_API_KEY"))


def generate_response(
    prompt: str, role: str = "user", model: str = "gemini-2.0-flash"
) -> str | None:
    """
    Generates a response from the Gemini model based on the given role and prompt.

    :param role: The role of the user in the conversation ('system', 'user', 'assistant')
    :param prompt: The input prompt for the model
    :param model: Type of Gemini model to use, defaults to gemini-2.0-flash
    :return: the content of the response generated by the model.
    """

    valid_roles = ["system", "user", "assistant"]

    if role not in valid_roles:
        log_error(
            _logger,
            f"Invalid role: {role}. Valid options are {', '.join(valid_roles)}.",
        )
        raise ValueError(
            f"Error: Invalid role. Please choose one of: {', '.join(valid_roles)}."
        )

    try:
        log_api_request(
            _logger,
            api_name="Gemini",
            endpoint="models.generate_content",
            params={"model": model, "role": role, "prompt_length": len(prompt)},
        )

        # Map roles: Gemini uses 'user' and 'model' (not 'assistant' or 'system')
        gemini_role = "model" if role in ("assistant", "system") else "user"

        response = client.models.generate_content(
            model=model,
            contents=genai.types.Content(
                parts=[genai.types.Part(text=prompt)],
                role=gemini_role,
            ),
        )

        response_text = response.text

        log_info(_logger, f"Prompt: {prompt}")
        log_api_response(
            _logger,
            api_name="Gemini",
            endpoint="models.generate_content",
            status_code=200,
            response_summary=f"Generated response with {len(response_text)} characters",
        )

        return response_text

    except Exception as e:
        log_error(_logger, "Unexpected error occurred during Gemini API call", exc=e)
        return None
