name: Python application test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
