name: Unit Test and Deployments

on: [push]

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.1
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest pytest-cov
        pip3 install -r requirements.txt
    - name: Test with pytest and generate coverage
      run: |
        make coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: docker build .

  Deploy:
    needs: [Unit_Test, Linter, Build-Docker-Image]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build and Deploy
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.IP_ADDRESS }}
        USER_NAME: ${{ secrets.USERNAME }}
      run: | 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          cd .. && cd /home/nearquake && 
          git pull origin master && 
          make up;
          '
