name: Unit Test and Deployments 

on: [push]

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.1
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest

  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.1
    - name: Install Black
      run: pip install black
    - name: Run Black
      run: black --check --verbose

  Deploy:
    needs: [Unit_Test, Linter]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
    - name: SSH into container 
      run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.USERNAME }}@${{ secrets.IP_ADDRESS }}

    - name: Navigate to the directory and deploy the latest change 
      run: |
        cd /home/ubuntu/nearquake && 
        git pull origin master && 
        sudo docker-compose up -d --build 
          
    - name: clean up images
      run: sudo docker image prune -f